---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nuts-and-bolts
  annotations:
    github.com/project-slug: hhru/nuts-and-bolts
  tags:
    - backend
    - java
spec:
  type: library
  lifecycle: production
